import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import { Analytics } from "@vercel/analytics/react"

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        >
        <Analytics/>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
